# Generated by Django 5.2 on 2026-04-19 00:26

import app.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import martor.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ollama',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(default='http://localhost:11434', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('default_model', models.CharField(blank=True, max_length=50, null=True)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.FloatField(default=0.7, help_text='Controls randomness in generation (higher = more random)')),
                ('num_ctx', models.PositiveIntegerField(default=4096, help_text='Context length size (number of tokens)')),
                ('num_predict', models.IntegerField(default=-1, help_text='Maximum number of tokens to generate (-1 = infinite)')),
            ],
            options={
                'verbose_name': 'Ollama',
                'verbose_name_plural': 'Ollama',
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('interval_mins', models.PositiveIntegerField(blank=True, help_text='Runs every X minutes', null=True, validators=[django.core.validators.MinValueValidator(5)])),
                ('cron_expression', models.CharField(blank=True, help_text='Scheduling in cron format', max_length=100, null=True, validators=[app.validators.validate_cron_expression])),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('ollama_model', models.CharField(blank=True, max_length=50, null=True)),
                ('system_prompt', martor.models.MartorField(blank=True, null=True)),
                ('telegram_bot_token', models.CharField(max_length=255, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_logs', to='app.bot')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('transport', models.CharField(choices=[('R', 'Remote'), ('L', 'Local')], max_length=1)),
                ('command', models.CharField(blank=True, help_text='Command to run (python, npx, uv)', max_length=10, null=True)),
                ('endpoint', models.URLField(blank=True, help_text='Remote MCP server endpoint URL', null=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('args', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, help_text='Command arguments as comma-seperated string (e.g: -y, @modelcontextprotocol/server-memory', null=True, size=None)),
                ('secrets', models.JSONField(blank=True, default=dict, help_text='Environment variables for local MCP server or HTTP headers for remote', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to='app.bot')),
            ],
            options={
                'verbose_name': 'MCP Server',
                'verbose_name_plural': 'MCP Servers',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('S', 'System'), ('U', 'User'), ('A', 'Assistant')])),
                ('intent', models.CharField(choices=[('J', 'Journal Entry'), ('R', 'Report Request'), ('Q', 'Question/Query'), ('O', 'Other')])),
                ('content', martor.models.MartorField()),
                ('channel', models.CharField(choices=[('S', 'SMS'), ('E', 'Email')])),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Sent'), ('F', 'Failed'), ('D', 'Delivered'), ('R', 'Received')], default='P')),
                ('is_report_request', models.BooleanField(default=False)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.bot')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
